name: For each commit and PR
on:
  push:
  pull_request:

jobs:
  validation-for-tinkerbell:
    if: github.event.repository.owner.loging == 'tinkerbell'
    runs-on: [self-hosted, X64]
    env:
      CGO_ENABLED: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: validate
        uses: ./.github/actions/build-test-push
        with:
          registry: quay.io
          namespace: tinkerbell
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_PASSWORD }}

  validation-for-forks:
    if: github.event.repository.owner.loging != 'tinkerbell'
    runs-on: [ubuntu-latest]
    env:
      CGO_ENABLED: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: validate
        uses: ./.github/actions/build-test-push
        with:
          registry: ${{ secrets.OCI_REGISTRY }}
          namespace: ${{ secrets.OCI_REGISTRY_NS }}
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_PASSWORD }}
